"""Behavioral PostgreSQL checks; every test owns a disposable schema."""

from __future__ import annotations

from collections.abc import Iterator
from concurrent.futures import ThreadPoolExecutor
from os import environ
from threading import Barrier
from uuid import uuid4

import pytest

from vectorstore import (
    CatalogChunk,
    CatalogDocument,
    EmbeddingPrice,
    EmbeddingSpec,
    PostgresDocumentCatalog,
    RetrievalScope,
)

pytestmark = pytest.mark.postgres_integration


@pytest.fixture
def catalog() -> Iterator[PostgresDocumentCatalog]:
    dsn = environ.get("VECTORSTORE_TEST_POSTGRES_DSN")
    if not dsn:
        if environ.get("VECTORSTORE_REQUIRE_POSTGRES_TESTS") == "1":
            pytest.fail("VECTORSTORE_TEST_POSTGRES_DSN is required for this job")
        pytest.skip(
            "set VECTORSTORE_TEST_POSTGRES_DSN to run PostgreSQL integration tests"
        )
    psycopg = pytest.importorskip("psycopg")
    schema = f"vectorstore_test_{uuid4().hex}"
    instance = PostgresDocumentCatalog(dsn, schema_name=schema)
    try:
        instance.create_schema()
        yield instance
    finally:
        # Only the schema generated by this fixture is ever removed.
        with psycopg.connect(dsn, autocommit=True) as connection:
            connection.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')


def seed(catalog: PostgresDocumentCatalog) -> None:
    catalog.upsert_documents(
        [
            CatalogDocument(
                "incident",
                tenant_id="acme",
                visibility="customer_safe",
                attributes={"priority": 3},
            ),
            CatalogDocument(
                "internal",
                tenant_id="acme",
                visibility="internal",
                attributes={"priority": 1},
            ),
            CatalogDocument(
                "other",
                tenant_id="other",
                visibility="customer_safe",
                attributes={"priority": 3},
            ),
        ]
    )
    catalog.upsert_chunks(
        [
            CatalogChunk(
                "incident-1", "incident", "INC-1104 certificate rotation login"
            ),
            CatalogChunk(
                "internal-1", "internal", "certificate rotation internal login"
            ),
            CatalogChunk("other-1", "other", "certificate rotation other login"),
        ]
    )


def test_schema_initialization_and_real_fts(catalog: PostgresDocumentCatalog) -> None:
    catalog.create_schema()
    catalog.validate_schema()
    seed(catalog)
    assert [hit.chunk_id for hit in catalog.search_lexical("INC-1104")] == [
        "incident-1"
    ]
    assert len(catalog.search_lexical('"certificate rotation"')) == 3
    assert catalog.search_lexical('"rotation certificate"') == []


def test_scope_and_filters_precede_top_k(catalog: PostgresDocumentCatalog) -> None:
    seed(catalog)
    scope = RetrievalScope(tenant_id="acme", visibility=("customer_safe",))
    filters = {"priority": {"$gte": 2}}
    assert [doc.doc_id for doc in catalog.find(filters, scope, limit=1)] == ["incident"]
    assert [
        hit.chunk_id
        for hit in catalog.search_lexical(
            "certificate",
            k=1,
            filter=filters,
            scope=scope,
        )
    ] == ["incident-1"]


def test_lifecycle_updates_and_delete_cascade(catalog: PostgresDocumentCatalog) -> None:
    seed(catalog)
    spec = EmbeddingSpec("test", "model", 3)
    chunk = catalog.get_chunks(["incident-1"])[0]
    assert chunk.content_hash is not None
    catalog.mark_embedded(chunk.chunk_id, spec, chunk.content_hash)
    assert "incident-1" not in catalog.stale_chunk_ids(spec)
    catalog.upsert_chunks(
        [CatalogChunk("incident-1", "incident", "updated signing metadata")]
    )
    assert "incident-1" in catalog.stale_chunk_ids(spec)
    assert catalog.search_lexical("INC-1104") == []
    assert catalog.search_lexical("signing")
    catalog.delete_documents(["incident"])
    assert catalog.get_chunks(["incident-1"]) == []
    assert catalog.embedding_state(spec.space_id, ["incident-1"]) == {}


def test_failed_write_rolls_back_all_chunks(catalog: PostgresDocumentCatalog) -> None:
    psycopg = pytest.importorskip("psycopg")
    catalog.upsert_documents([CatalogDocument("valid")])
    with pytest.raises(psycopg.errors.ForeignKeyViolation):
        catalog.upsert_chunks(
            [
                CatalogChunk("first", "valid", "would otherwise be inserted"),
                CatalogChunk("second", "nonexistent", "invalid foreign key"),
            ]
        )
    assert catalog.get_chunks(["first", "second"]) == []


def test_concurrent_sessions_cannot_overspend(catalog: PostgresDocumentCatalog) -> None:
    barrier = Barrier(2)
    price = EmbeddingPrice.from_usd_per_million("test", "model", "1", version="test-v1")

    def reserve() -> bool:
        instance = PostgresDocumentCatalog(
            environ["VECTORSTORE_TEST_POSTGRES_DSN"],
            schema_name=catalog.schema_name,
        )
        barrier.wait(timeout=10)
        decision = instance.reserve(
            price.charge(600_000),
            daily_limit_nanos=1_000_000_000,
            monthly_limit_nanos=None,
            ttl_seconds=300,
        )
        return decision.reservation is not None

    with ThreadPoolExecutor(max_workers=2) as executor:
        futures = [executor.submit(reserve), executor.submit(reserve)]
        assert sorted(future.result(timeout=20) for future in futures) == [False, True]
    assert catalog.spent_today_nanos() == 600_000_000


def test_budget_commit_and_release_survive_reopening(
    catalog: PostgresDocumentCatalog,
) -> None:
    price = EmbeddingPrice.from_usd_per_million("test", "model", "1", version="test-v1")
    first = catalog.reserve(
        price.charge(600_000),
        daily_limit_nanos=1_000_000_000,
        monthly_limit_nanos=None,
        ttl_seconds=300,
    ).reservation
    assert first is not None
    catalog.commit(first, price.charge(200_000))
    second = catalog.reserve(
        price.charge(600_000),
        daily_limit_nanos=1_000_000_000,
        monthly_limit_nanos=None,
        ttl_seconds=300,
    ).reservation
    assert second is not None
    catalog.release(second)
    reopened = PostgresDocumentCatalog(
        environ["VECTORSTORE_TEST_POSTGRES_DSN"], schema_name=catalog.schema_name
    )
    assert reopened.spent_today_nanos() == 200_000_000
    assert reopened.tokens_today("test") == 200_000
