"""Extensible vector storage and semantic search."""

from .catalog import (
    CatalogChunk,
    CatalogDocument,
    DocumentCatalog,
    EmbeddingState,
    LexicalUnavailableError,
    RankedHit,
    RetrievalScope,
    SqliteDocumentCatalog,
)
from .config import build_retriever
from .embeddings import (
    BudgetLedger,
    CircuitBreaker,
    EmbeddingProvider,
    EmbeddingRouter,
    EmbeddingSpec,
    InMemoryBudgetLedger,
    NoProviderAvailableError,
    OpenAIEmbedding,
    ProviderSelection,
    SelectionReason,
    SentenceTransformerEmbedding,
)
from .hybrid import (
    QueryAnalyzer,
    QueryKind,
    QueryProfile,
    RetrievalHit,
    RetrievalResult,
    RetrievalTimings,
    Retriever,
    RetrieverConfig,
    rrf,
)
from .index import VectorIndex
from .models import Chunk, MetadataFilter, MetadataValue, SearchResult
from .observability import NoOpRetrievalObserver, RetrievalTraceObserver
from .records import Record, content_hash, semantic_projection
from .stores import (
    AzureSqlVectorStore,
    ChromaVectorStore,
    FaissVectorStore,
    NumpyVectorStore,
    VectorStore,
    create_store,
    register_store,
)

__all__ = [
    "AzureSqlVectorStore",
    "BudgetLedger",
    "CatalogChunk",
    "CatalogDocument",
    "ChromaVectorStore",
    "Chunk",
    "CircuitBreaker",
    "DocumentCatalog",
    "EmbeddingProvider",
    "EmbeddingRouter",
    "EmbeddingSpec",
    "EmbeddingState",
    "FaissVectorStore",
    "InMemoryBudgetLedger",
    "LexicalUnavailableError",
    "MetadataFilter",
    "MetadataValue",
    "NoOpRetrievalObserver",
    "NoProviderAvailableError",
    "NumpyVectorStore",
    "OpenAIEmbedding",
    "ProviderSelection",
    "QueryAnalyzer",
    "QueryKind",
    "QueryProfile",
    "RankedHit",
    "Record",
    "RetrievalHit",
    "RetrievalResult",
    "RetrievalScope",
    "RetrievalTimings",
    "RetrievalTraceObserver",
    "Retriever",
    "RetrieverConfig",
    "SelectionReason",
    "SentenceTransformerEmbedding",
    "SearchResult",
    "SqliteDocumentCatalog",
    "VectorIndex",
    "VectorStore",
    "build_retriever",
    "content_hash",
    "create_store",
    "register_store",
    "rrf",
    "semantic_projection",
]
